name: RipSecrets
on: [pull_request]
jobs:
  ripsecrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download ripsecrets
        run: |
          wget https://static.bombbomb.com/ci/ripsecrets.tar.gz
          tar -xzf ripsecrets.tar.gz
          chmod +x ripsecrets
          sudo mv ripsecrets /usr/local/bin

      - name: Run ripsecrets
        run: |
          ripsecrets `git diff origin/${{ github.base_ref }} --name-only --diff-filter=ACM`